---
title: "DATA*6200 Assignment 2"
author: "Dr. Justin Slater"
format: html
---

# Learning Objectives

This assignment is meant to reinforce and assess the following skills:

- Intermediate data wrangling skills in R, including
    - Basic webscraping
    - Geospatial data wrangling
- Telling stories with data
- Visualizing data over space and time
- Critical thinking skills

# Your task

Wildfires are a growing concern in Canada, particularly in British Columbia (B.C). Resultingly, the B.C government has records of all substantial fires [historically (2012-2017)](https://www2.gov.bc.ca/gov/content/safety/wildfire-status/about-bcws/wildfire-statistics), and [currently](https://www2.gov.bc.ca/gov/content/safety/wildfire-status/about-bcws/disclaimer).

In this assignment, I want you to analyze the wildfire distribution in B.C over time from 2012-2017, and compare this to the current data. I also want you to determine what climate and environmental factors increase impact fire likelihood.

To do this, take the following steps:

1. Scrape the 2012-2017 data using methods we used in class.
2. Pull temperature and elevation data for B.C using the `geodata` package. Crop and mask as needed.
3. Visualize wildfires over time between 2012-2017 overtop a temperature raster.
4. Use a maximum of two visualizations to answer the question: how do temperature/elevation impact fire occurence?
5. How does the historical distribution (2012-2017) of wildfires differ from this year's (2024) wildfires?

Your visualizations should be standalone, but complete answers to the questions will also involve written descriptions. These written descriptions should include a discussion of data/analysis limitations.

# Submission

You should submit a .rmd/.qmd file (not a presentation) that contains all code used to wrangle the data and produce visualizations. You should knit/compile to an html file, which should contain visualizations, key code chunks, and brief written descriptions of your answers.

You can organize your document into sections corresponding to the question numbers, or in any other reasonable way.

## Tips

- Be concise and specific. Concise code and descriptions are your best friend. Please do not submit ChatGPT "valuable insights" paragraphs that could apply to any analysis. When discussing data limitations, try to offer specific limitations about **these data**, not limitations that could be said about any data. E.g rather than say "there are missing values", you may discuss **how** missingness impacts your ability to answer one of the questions, and what the impact may be.
- Use methods shown in class wherever possible. 
- Take pride in your final report's format.
- Use descriptive figure captions for complex visualizations.

# Grading Scheme [45 marks total]

The following rubric depicts the grade breakdown for this assignment, followed by statements that are consistent with certain grade levels. Please note that a more detailed rubric will be used for grading. However, we do not provide you with a more detailed rubric at this stage, because this would give too many clues on how the assignment should be done. Also note that although these statements are guidelines for what a strong assignment submission looks like, the final grade is ultimately made at the discretion of the instructor/TA.

### Code quality [10 points]

*Note: It is your job to know what good coding practices are based on the lectures/readings.*

- [9-10] Code is clear and concise, and lacks unnecessary repetition. Code clearly demonstrates the techniques learned in class, and follows good programming practices. The code is well documented and easy to follow. 
- [7-8] Code is mostly clear and concise, but tends to over-rely on one or two techniques. The code is mostly well documented, but some comments are missing. "Over-commenting" may be present.
- [5-6] Code "gets the job done" but is very hard to follow or includes unnecessary chunks. Methods from outside the class are implemented with no explanation or description.
- [<5] inadequate

### Data Processing Decisions [10 marks]

- [9-10] Data cleaning and processing decisions are well-justified in context of research question(s). The student made extra effort to get the most out of the data at hand. Data is formatted according to principles discussed in class.
- [7-8] Most data cleaning/processing decisions are justified, with some processing decisions potentially being misguided. Data is formatted according to principles discussed in class, with 1 or 2 noticeable inaccuracies.
- [5-6] Data cleaning/processing decisions are not well justified. Many observations are binned or discarded without much thought. Data is not well formatted after processing.
- [<5] Inadequate

## Data visualizations and descriptions [20 marks]

- [18-20] Visualizations are attractive, well captioned and mostly convey their point on their own. Good graphing principles are followed in all visualizations, applying advanced ggplot features when necessary. Arguments and descriptions accompanying each figure are clear and concise, are specific to the problem at hand, and help convey the student's point. Figure captions are well utilized. Limitation of the data/analysis are clearly described in the context of the questions.
- [14-17] Visualizations are mostly attractive, with minor unclear elements. Good graphing principles are mostly followed in some visualizations, but not in others. Arguments and descriptions accompanying the figures are mostly clear and concise, but may be more vague than necessary. Figure Captions are utilized, but may not tell the whole story. Limitation of the data/analysis are described mostly in the context of the questions.
- [10-13] Visualizations lack clarity in key areas, and are hard to interpret without additional explanation. Arguments and descriptions accompanying the visualizations are vague or are irrelevant to answering the research questions(s). Captions are not used or are misapplied. Limitation of the data/analysis are vague and not specific to the questions posed.
- [<10] Inadequate

## Formatting and Reproducibility [5 marks]

- [5] The analysis was reproducible with minimal effort. Results from the reproduced file match those from the submitted file. The document is easy to follow and is professionally presented.
- [3-4] The analysis required substantial effort to reproduce. There are minor discrepancies between the submitted file and reproduced file. The document is mostly well-presented.
- [0-2] Analysis was not reproducible or required consultation with the student to reproduce it. The document is not easy to follow and is not visually attractive.

